/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/AppLayout.vue')['default']
    AuthGuard: typeof import('./components/AuthGuard.vue')['default']
    DataList: typeof import('./components/DataList.vue')['default']
    Error: typeof import('./components/Error.vue')['default']
    MenuItem: typeof import('./components/MenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskRunner: typeof import('./components/TaskRunner.vue')['default']
    Waiting: typeof import('./components/Waiting.vue')['default']
  }
}
