/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/customer/': RouteRecordInfo<'/customer/', '/customer', Record<never, never>, Record<never, never>>,
    '/customer/[id]': RouteRecordInfo<'/customer/[id]', '/customer/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/customer/create': RouteRecordInfo<'/customer/create', '/customer/create', Record<never, never>, Record<never, never>>,
    '/device/': RouteRecordInfo<'/device/', '/device', Record<never, never>, Record<never, never>>,
    '/device/[id]': RouteRecordInfo<'/device/[id]', '/device/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/password': RouteRecordInfo<'/password', '/password', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/shop/': RouteRecordInfo<'/shop/', '/shop', Record<never, never>, Record<never, never>>,
    '/shop/[id]': RouteRecordInfo<'/shop/[id]', '/shop/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/shop/create': RouteRecordInfo<'/shop/create', '/shop/create', Record<never, never>, Record<never, never>>,
    '/user/': RouteRecordInfo<'/user/', '/user', Record<never, never>, Record<never, never>>,
    '/user/[id]': RouteRecordInfo<'/user/[id]', '/user/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/user/create': RouteRecordInfo<'/user/create', '/user/create', Record<never, never>, Record<never, never>>,
    '/vehicle/': RouteRecordInfo<'/vehicle/', '/vehicle', Record<never, never>, Record<never, never>>,
    '/vehicle/[id]': RouteRecordInfo<'/vehicle/[id]', '/vehicle/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/vehicle/create': RouteRecordInfo<'/vehicle/create', '/vehicle/create', Record<never, never>, Record<never, never>>,
  }
}
